### ISSUE TITLE
Web Page - CloudWatch graphics with no data (metrics)

### ISSUE THREAD

**Issue by badrgit** [aws-samples/aws-cloudwatch-building-dashboard-outside-aws-console#1]
Hi !

I followed the steps of your blog and I get as a result a web page (Chrome - http://localhost:8080/) diplaying CloudWatch graphics without data (empty). Supervised instances are started with metrics generated in the CloudWatch Dashboards. Also, the index.html file is well configured (Instance_ID, API_GATEWAY_URL, API_KEY, Account_ID).

Do you have an idea of ​​the problem ?
Thank you.

Regards,

**Comment by wisemanIV** [comment]
If you can see the metric in the CloudWatch dashboard it should be the same in the snapshot. 
You should check that X and Y axis of your snapshot match what you see in CloudWatch, i.e. the min / max values of the axis are the same. 

Do you see any errors in the API GateWay logs or the Lambda logs? You will find them in the Logs tab of the CloudWatch console.

**Comment by badrgit** [comment]
I change the Y axis values and now it works! Thank you.
