### ISSUE TITLE
Errors in CloudFormation

### ISSUE THREAD

**Issue by kevinjardine** [aws-samples/aws-cloudwatch-building-dashboard-outside-aws-console#6]
When I try to run this in CloudFormation I get two errors;

'code.s3Bucket' failed to satisfy constraint: 
Member must satisfy regular expression pattern: ^[0-9A-Za-z\.\-_]*(?<!\.)$; 
Member must have length less than or equal to 63

Any suggestions?

**Comment by jonasmcferreira** [comment]
Same here

**Comment by wisemanIV** [comment]
The S3 bucket parameter is a type String. Does your bucket name include any special characters outside of the pattern? ^[0-9A-Za-z.-_]*(?<!.)$;

Dropping the Type from the parameter should allow you to proceed. 

"LambdaS3Bucket": {
      "Description" : "Name of an S3 bucket containing snapshotwidgetdemo.zip",
      "Type" : "String",
      "ConstraintDescription" : "Must be a valid S3 bucket"
    },

**Comment by kevinjardine** [comment]
OK, thanks. I ended up writing my own CloudWatch code, which is now in production.
